site_name: java-tron
site_url: https://tronprotocol.github.io/documentation-en/
repo_url: https://github.com/tronprotocol/documentation-en

nav:
    - Home: index.md
    - Getting Started With java-tron:
        - Getting Started: getting_started/getting_started_with_javatron.md
    - Using java-tron:
        - Deploying: using_javatron/installing_javatron.md
        - Backup and Restore: using_javatron/backup_restore.md
        - Lite FullNode: using_javatron/litefullnode.md
        - Private Network: using_javatron/private_network.md
        - Event Subscription: architecture/event.md
        - Database Configuration: architecture/database.md
        - Network Connection: using_javatron/connecting_to_tron.md
        - Node Monitoring: using_javatron/metrics.md
        - Node Maintenance Tool: using_javatron/toolkit.md
    - API:
        - HTTP API: api/http.md
        - gRPC API: api/rpc.md
        - jsonRPC API: api/json-rpc.md
    - Core Protocol:
        - DPoS: mechanism-algorithm/dpos.md
        - Super Representative: mechanism-algorithm/sr.md
        - Account Model: mechanism-algorithm/account.md
        - Resource Model: mechanism-algorithm/resource.md
        - Smart Contract: contracts/contract.md
        - System Contract: mechanism-algorithm/system-contracts.md
        - Decentralized Exchange: mechanism-algorithm/dex.md
        - Account Permission Management: mechanism-algorithm/multi-signatures.md
    - For java-tron Developers:
        - Developer Guide: developers/java-tron.md
        - TIPs Workflow: developers/tips.md
        - Issue Workflow: developers/issue-workflow.md
        - Governance Workflow: developers/governance.md
        - Configure the IDE: developers/run-in-idea.md
        - Development Example: developers/demo.md
        - Core Modules: developers/code-structure.md
    - For Dapp Developers:
        - Tools: contracts/tools.md
    - Clients:
        - wallet-cli: clients/wallet-cli.md
    - Releases:
        - Deployment Manual for the New Version: releases/upgrade-instruction.md
        - Integrity Check: releases/signature_verification.md
        - History:
            - releases/versions/index.md
            - v4.8.1 (Democritus): releases/versions/v4.8.1.md
            - v4.8.0.1 (Seneca): releases/versions/v4.8.0.1.md
            - v4.8.0 (Kant): releases/versions/v4.8.0.md
            - v4.7.7 (Epicurus): releases/versions/v4.7.7.md
            - v4.7.6 (Anaximander): releases/versions/v4.7.6.md
            - v4.7.5 (Cleobulus): releases/versions/v4.7.5.md
            - v4.7.4 (Bias): releases/versions/v4.7.4.md
            - v4.7.3.1 (Solon): releases/versions/v4.7.3.1.md
            - v4.7.3 (Chilon): releases/versions/v4.7.3.md
            - v4.7.2 (Periander): releases/versions/v4.7.2.md
            - v4.7.1.1 (Pittacus): releases/versions/v4.7.1.1.md
            - v4.7.1 (Sartre): releases/versions/v4.7.1.md
            - v4.7.0.1 (Aristotle): releases/versions/v4.7.0.1.md
            - v4.6.0 (Socrates): releases/versions/v4.6.0.md
            - v4.5.2 (Aurelius): releases/versions/v4.5.2.md
            - v4.5.1 (Tertullian): releases/versions/v4.5.1.md
            - v4.4.6 (David): releases/versions/v4.4.6.md
            - v4.4.5 (Cicero): releases/versions/v4.4.5.md
            - v4.4.4 (Plotinus): releases/versions/v4.4.4.md
            - v4.4.2 (Augustinus): releases/versions/v4.4.2.md
            - v4.4.0 (Rousseau): releases/versions/v4.4.0.md
            - v4.3.0 (Bacon): releases/versions/v4.3.0.md
            - v4.2.2.1 (Epictetus): releases/versions/v4.2.2.1.md
            - v4.2.2 (Lucretius): releases/versions/v4.2.2.md
            - v4.2.0 (Plato): releases/versions/v4.2.0.md
            - v4.1.3 (Thales): releases/versions/v4.1.3.md
            - v4.1.2: releases/versions/v4.1.2.md
            - v4.1.1: releases/versions/v4.1.1.md
            - v4.0.0: releases/versions/v4.0.0.md
            - Odyssey-v3.7: releases/versions/v3.7.md
            - Odyssey-v3.6.5: releases/versions/v3.6.5.md
    - Appendix:
        - Glossary: glossary.md

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.sections  # Enable grouping in the left navigation bar
    - navigation.footer
    - navigation.indexes   # Subgroup titles like History open index.md directly
    - toc.integrate
    - search.highlight  # Highlight matching content during search
    - search.suggest  # Show suggestions during search
    - content.code.annotate  # Code block annotations
    - content.tooltips  # Tooltips in content
  palette:
    primary: custom  # Primary color
    accent: custom  # Accent color
  font:
    text: Roboto  # Body text font
    code: Roboto Mono  # Code font

extra_javascript:
    - javascripts/toc.js
    - javascripts/nav-toc.js
    - javascripts/mathjax-sri.js

extra_css:
    - stylesheets/extra.css

markdown_extensions:
    - admonition
    - footnotes
    - codehilite
    - toc:
        permalink: true
        toc_depth: 3
    - pymdownx.arithmatex
    - pymdownx.tilde
    - pymdownx.tasklist
    - pymdownx.superfences

plugins:
  - search
  - exclude:
      glob:
        - clients/tron-grid.md
        - contracts/trc20.md
        - contracts/tvm.md
        - developers/contribution.md
        - developers/gpg.md
        - developers/incentives.md
        - developers/resources.md
        - faq/index.md
        - introduction/index.md
        - introduction/overview.md
        - mechanism-algorithm/shielded-TRC20-contract.md
        - mechanism-algorithm/trc10.md

